version: '3.8'  
services:
  web:
    image: fernandovasori/tickets_service-web 
    ports:
      - "5000:5000"                         
    environment:
      FLASK_APP: app.py                   
      FLASK_ENV: development               